package main

const EMAIL_HOST = "EMAIL_HOST"
const EMAIL_PORT = "EMAIL_PORT"
const EMAIL_USERNAME = "EMAIL_USERNAME"
const EMAIL_PASSWORD = "EMAIL_PASSWORD"
const EMAIL_ENCRYPTION = "EMAIL_ENCRYPTION"
